### ISSUE TITLE
Error when using RandomTeleport on MC 1.13.1

### ISSUE THREAD

**Issue by Rocologo** [Phoenix616/RandomTeleport#24]
[13:59:04] [Server thread/WARN]: [ServerSigns] Error while executing task PlayerTask{data='rtp survival Rocologo'} de.czymm.serversigns.taskmanager.tasks.PlayerActionTask@32e27f12
org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin RandomTeleport v1.7.4 (build #24)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at de.czymm.serversigns.ServerSignsPlugin.serverCommand(ServerSignsPlugin.java:175) ~[?:?]
	at de.czymm.serversigns.taskmanager.tasks.PlayerActionTask.runPlayerTask(PlayerActionTask.java:30) ~[?:?]
	at de.czymm.serversigns.taskmanager.tasks.PlayerTask.runTask(PlayerTask.java:34) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTaskImpl(TaskManagerTaskExecutor.java:45) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTask(TaskManagerTaskExecutor.java:38) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTask(TaskManagerTaskExecutor.java:14) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManager.addTask(TaskManager.java:91) ~[?:?]
	at de.czymm.serversigns.signs.ServerSignExecutor.executeSignFull(ServerSignExecutor.java:103) ~[?:?]
	at de.czymm.serversigns.listeners.PlayerListener.playerInteractCheck(PlayerListener.java:60) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:240) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:207) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.BlockPressurePlateBinary.b(BlockPressurePlateBinary.java:75) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:66) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:59) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.IBlockData.a(SourceFile:269) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:940) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:852) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:880) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin RandomTeleport v1.7.4 (build #24)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.onCommand(RandomTeleport.java:233) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	... 39 more
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.checkforRegion(RandomTeleport.java:738) ~[?:?]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.teleportCheck(RandomTeleport.java:716) ~[?:?]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.onCommand(RandomTeleport.java:561) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.onCommand(RandomTeleport.java:233) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	... 39 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WGBukkit
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.checkforRegion(RandomTeleport.java:738) ~[?:?]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.teleportCheck(RandomTeleport.java:716) ~[?:?]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.onCommand(RandomTeleport.java:561) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	at de.themoep.bukkit.plugin.RandomTeleport.RandomTeleport.onCommand(RandomTeleport.java:233) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
	... 39 more

**Comment by Phoenix616** [comment]
This is due to you using an incompatible WorldGuard (it only supports WorldGuard6). WorldGuard 7 support will be added with the [2.0 rewrite](https://github.com/Phoenix616/RandomTeleport/milestone/1).

**Comment by Phoenix616** [comment]
Since then WorldGuard 7 support has been added to the legacy version so this should be fixed.
