### ISSUE TITLE
Error on Paper #282

### ISSUE THREAD

**Issue by Axer22** [Phoenix616/RandomTeleport#35]
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89) ~[patched_1.15.2.jar:git-Paper-282]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAtAsync(CraftWorld.java:2476) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.World.getChunkAtAsync(World.java:702) ~[patched_1.15.2.jar:git-Paper-282]
	at de.themoep.randomteleport.libs.paperlib.features.asyncchunks.AsyncChunksPaper_13.getChunkAtAsync(AsyncChunksPaper_13.java:11) ~[?:?]
	at de.themoep.randomteleport.libs.paperlib.environments.Environment.getChunkAtAsync(Environment.java:75) ~[?:?]
	at de.themoep.randomteleport.libs.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:132) ~[?:?]
	at de.themoep.randomteleport.libs.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:107) ~[?:?]
	at de.themoep.randomteleport.searcher.RandomSearcher.checkRandom(RandomSearcher.java:376) ~[?:?]
	at de.themoep.randomteleport.searcher.RandomSearcher.lambda$search$0(RandomSearcher.java:330) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1253) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1170) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:959) ~[patched_1.15.2.jar:git-Paper-282]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at java.util.Optional.<init>(Optional.java:107) ~[?:?]
	at java.util.Optional.of(Optional.java:120) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.left(Either.java:54) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.lambda$getChunkAtAsync$8(CraftWorld.java:2477) ~[patched_1.15.2.jar:git-Paper-282]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 19 more
```
This error is happening on #282 paper when I use /rtp. I've updated from #201 and on that version worked fine.

**Comment by Phoenix616** [comment]
This does not look like an error in the plugin but with your server itself when trying to load a specific chunk, I suggest reporting that to paper.

If this doesn't happen on every random teleport then this might just be an issue with a single chunk so you not noticing it before makes some sense (as the chunk is random) and might not be related to the paper update.

**Comment by Phoenix616** [comment]
This issue has since been fixed by paper.
