### ISSUE TITLE
Search NPEs on world without border

### ISSUE THREAD

**Issue by Artuto** [Phoenix616/RandomTeleport#56]
#### Plugin Version

 ```
version randomteleport
[22:59:09 INFO]: RandomTeleport version 2.0-SNAPSHOT (build 99)
```
 
#### Environment description

 Minecraft 1.19.3
 
#### Full Log

```
[22:55:23 ERROR]: [RandomTeleport] Error while trying to find a location!
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.popcraft.chunkyborder.BorderData.getBorder()" because "borderData" is null
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.lambda$getChunkAtAsync$15(CraftWorld.java:2362) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[prismarine-1.19.3.jar:git-Prismarine-14]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.popcraft.chunkyborder.BorderData.getBorder()" because "borderData" is null
        at de.themoep.randomteleport.hook.plugin.ChunkyBorderHook.isInsideBorder(ChunkyBorderHook.java:40) ~[RandomTeleport-minebench-b99.jar:?]
        at de.themoep.randomteleport.hook.HookManager.isInsideBorder(HookManager.java:176) ~[RandomTeleport-minebench-b99.jar:?]
        at de.themoep.randomteleport.searcher.validators.WorldborderValidator.validate(WorldborderValidator.java:32) ~[RandomTeleport-minebench-b99.jar:?]
        at de.themoep.randomteleport.searcher.RandomSearcher.lambda$checkRandom$3(RandomSearcher.java:470) ~[RandomTeleport-minebench-b99.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 16 more
```

#### What other programs/plugins are you running?
ChunkyBorder v1.1.42

#### What is happening?
When trying to teleport in a world without a world border

#### What did you expect to happen?

Not error

**Comment by Artuto** [comment]
Bump
